#!/usr/bin/env ruby

disable_dbus = ARGV.delete '--no-dbus'
disable_drb = ARGV.delete '--no-drb'

require 'drb' unless disable_drb
require File.join(File.dirname(__FILE__), 'dbus-interface') unless disable_dbus

if ARGV.any?
  if ARGV.delete 'nowplaying'
    DRb.start_service
    client = DRbObject.new nil, 'druby://localhost:68739'
    info = client.now_playing
    if info
      puts "#{info['SongName'] || info['Name']} - #{info['ArtistName']} - #{info['AlbumName']}"
    else
      puts "No song is playing"
    end
    exit
  end
end

require File.join(File.dirname(__FILE__), 'client')
require File.join(File.dirname(__FILE__), 'mplayer')
require File.join(File.dirname(__FILE__), 'ui')

client = GrooveShark::Client.new
$session = client.session

run_dbus client unless disable_dbus
DRb.start_service 'druby://localhost:68739', client unless disable_drb

#~ puts "Enter a search query:"
#~ query = gets.chomp
#~ puts
#~ puts "Searching for \"#{query}\":"
#~ results = client.search_songs(query)['Return']
#~ results.each do |result|
  #~ puts "#{results.index result} - #{result['Name']} - #{result['ArtistName']} - #{result['AlbumName']}"
#~ end
#~ 
#~ puts
#~ puts "Please type in a song index to [attempt to] play it:"
#~ index = gets.to_i
#~ 
#~ client.queue << results[index]
#~ Thread.new do
  #~ client.queue.play_radio
#~ end

display = client.display = Remora::UI::Display.new(client)

trap 'INT' do
  display.undo_modes
  exit
end

begin
  display.pane :queue, 1, 1, 20, -1, 'Queue' do
    control :songs, Remora::UI::ListBox, 1, 1, -1, -1 do
      number!
    end
  end

  display.pane :main, 20, 1, -1, -15, 'Search results' do
    display.active_control = control :search, Remora::UI::TextBox, 2, 1, -2, 1 do
      self.label = 'Search'
      self.text = ''
    end
    control :results, Remora::UI::ListBox, 1, 2, -1, -1 do
      number!
    end
  end

  display.pane :log, 20, -15, -1, -5, 'MPlayer Output' do
    control :output, Remora::UI::ListBox, 2, 1, -2, -1
  end

  display.pane :np, 20, -5, -1, -1, 'Now playing' do
    control :song_name, Remora::UI::Label, 1, 1, -1, 1 do
      align :center
    end
    control :cue, Remora::UI::ProgressBar, 2, 2, -2, 3 do
      template '==>  '
    end
    control :position, Remora::UI::Label, 1, 3, -1, 3
  end
  
  results = nil
  display.panes[:main].controls[:search].on_submit do |query|
    next if query.empty?
	
    if query.to_i.to_s == query && results
      index = query.to_i - 1
      next if index < 0 || index > results.size
      
      song = results[index]
      client.queue << song
      
      unless client.now_playing
        Thread.new do
          begin
            client.queue.play_radio
          rescue => ex
            display.undo_modes
            puts ex.class, ex.message, ex.backtrace
            exit
          end
        end
      end
    else
      results = client.search_songs(query)['Return']
      display.panes[:main].controls[:results].data = results.map do |result|
        "#{result['Name']} - #{result['ArtistName']} - #{result['AlbumName']}"
      end
      display.panes[:main].title = "Search Results for #{query}"
      display.dirty! :main
    end
  end

  display.handle while sleep 0.01

rescue => ex
  display.undo_modes
  puts ex.class, ex.message, ex.backtrace
  exit
end
